# fly.toml app configuration file generated for python-get-weather on 2023-07-22T17:48:53-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "python-get-weather"
primary_region = "sea"

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
